### PR TITLE
Add WireBeGone and VRLogixRotateFix

### PR DESCRIPTION
**Pull request by AlexW-578**
Hi,

I've added my mod [VRLogixRotateFix](https://github.com/AlexW-578/VRLogixRotateFix) and a new mod called WireBeGone as patches.

WireBeGone allows the user to deactivate the wire connecting the Logix Interface to their target.
VRLogixRotateFix allows spawning Logix node at the same rotation as the user when in VR

### CODE REVIEW

**Comment by badhaloninja** [comment]
I am sorry I missed this, github is not very good at notifying me if I am not actively checking.
I'll check this out probably later today

**Comment by AlexW-578** [comment]
Ye, no worries take your time

**Comment by badhaloninja** [comment]
What about putting a wire toggle on the interface itself and it defaulting to having the wire off?
wire toggle demo

**Comment by AlexW-578** [comment]
That's a really good idea that I didn't even think about.
That would make it easier for when you want to toggle everything.

**Comment by AlexW-578** [comment]
Just tested this, works exactly like shown. Way better than the original method of toggling them, thank you

**Comment by badhaloninja** [comment]
Currently just waiting for this to get reviewed neos-modding-group/neos-mod-manifest/pull/345

**Pull request merged**
